server:
  port: 8081
spring:
    data:
      jpa:
        repositories:
             bootstrap-mode: default
    jpa: 
      database-platform:  org.hibernate.dialect.H2Dialect 
    datasource: 
      url: jdbc:h2:mem:testdb1
      driverClassName: org.h2.Driver
      username: sa
      password: password
    h2:
       console: 
             enabled: true
